/*
 * delays.h
 *
 *  Created on: Dec 15, 2019
 *      Author: marco
 */

#ifndef DELAYS_H_
#define DELAYS_H_

/*
 * This is a function written in assembly to perform e delay by drecrementing
 * a variable until its value is zero. The delay generated by this function,
 * measured with -O2 optimization in a simple toggling example, approximates
 * the function:
 *  t = 1.25e-7 * d + 1.65e-7,
 * where t is the time delay and d is the argument of the delaysSub function,
 * a 32-bit unsigned integer.
 */
extern void delaysSub(uint32_t);


#endif /* DELAYS_H_ */
