/*
 * delays.h
 *
 *  Created on: Dec 15, 2019
 *      Author: marco
 */

#ifndef DELAYS_H_
#define DELAYS_H_

//===========================================================================
/*------------------------------- Functions -------------------------------*/
//===========================================================================
//---------------------------------------------------------------------------
/**
 * @brief Generates 6 cycles of clock of delay per count.
 *
 * This is a function written in assembly to perform a delay by decrementing
 * a variable until its value is zero. The delay generated by this function
 * is approximately 6 cycles of clock per count. The delay passed to the
 * function is a 32-bit unsigned integer.
 *
 * There is an small error in the final generated delay. For small values of
 * clock cycles, the error will be around 2% and converges to around 0.2% for
 * large values.
 *
 * @param delay Delay to be generated, as a multiple of 6 clock cycles.
 */
extern void delaysLoop(uint32_t);
//---------------------------------------------------------------------------
/**
 * @brief Generates delays in microseconds.
 *
 * It is assumed that the clock is 72 MHz.
 *
 * There is an small error in the final generated delay. For small values of
 * clock cycles, the error will be around 2% and converges to around 0.2% for
 * large values.
 *
 * @param delay Delay to be generated, in microseconds.
 */
extern void delaysus(uint32_t);
//---------------------------------------------------------------------------
//===========================================================================

#endif /* DELAYS_H_ */
