/*
 * delays.h
 *
 *  Created on: Dec 15, 2019
 *      Author: marco
 */

#ifndef DELAYS_H_
#define DELAYS_H_

/*
 * This is a function written in assembly to perform a delay by drecrementing
 * a variable until its value is zero. The delay generated by this function
 * is approximately 7 cycles of clock per count (measured at 72 MHz). The 
 * delay passed to the function is a 32-bit unsigned integer.
 */
extern void delaysSub(uint32_t);


#endif /* DELAYS_H_ */
